spring:
  datasource:
    url: jdbc:h2:~/data/eatgo
#    :DB_CLOSE_ON_EXIT=FALSE

  jpa:
    hibernate:
      ddl-auto: update

jwt:
  secret: 12345678901234567890123456789012
---

spring:
  profiles: test
  datasource:
    url: jdbc:h2:mem:test
